# Generated by Django 4.2.7 on 2023-12-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revision_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='RevisionCheckbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesapp.revision')),
            ],
        ),
    ]
