# Generated by Django 4.2.7 on 2023-12-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0006_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
